### ISSUE TITLE
Can't install on latest macOS

### ISSUE THREAD

**Issue by steals** [codeclimate/homebrew-formulae#29]
When I try to install codeclimate on the latest macOs I got the following error:
```
~ ❯❯❯ brew install codeclimate                                                                                                                                                                         ✘ 1
==> Installing codeclimate from codeclimate/formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.71.1.tar.gz
Already downloaded: /Users/steals/Library/Caches/Homebrew/codeclimate-0.71.1.tar.gz
==> make install
Last 15 lines from /Users/steals/Library/Logs/Homebrew/codeclimate/01.make:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Unable to run `docker version', the docker daemon may not be running
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
bin/check: line 11: [: : integer expression expected
Please ensure `docker version' succeeds and try again
make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/codeclimate/homebrew-formulae/issues
```

I have docker installed from brew (not from brew cask) and can successfully run _docker version_ or _docker ps_ in the same terminal where I try to install codeclimate.
Also I can successfully execute "make" command if I manually download codeclimate archive and extract it.

**Comment by casi** [comment]
Hi, I have a similar problem on Mac OS X El Capitan (10.11.6): 
```
$ brew upgrade codeclimate
==> Upgrading 1 outdated package, with result:
codeclimate/formulae/codeclimate 0.71.1 -> 0.71.2
==> Upgrading codeclimate/formulae/codeclimate 
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.71.2.tar.gz
Already downloaded: /Users/carsten/Library/Caches/Homebrew/codeclimate-0.71.2.tar.gz
==> make install
Last 15 lines from /Users/carsten/Library/Logs/Homebrew/codeclimate/01.make:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Unable to run `docker version', the docker daemon may not be running
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
bin/check: line 11: [: : integer expression expected
Please ensure `docker version' succeeds and try again
make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/codeclimate/homebrew-formulae/issues

Error: undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x0000010212a7e8>
Did you mean?  check_for_tap_ruby_files_locations
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:157:in `rescue in upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:169:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:95:in `block in upgrade'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by casi** [comment]
Ok, I tried again with the latest Docker Client (CE Version 18.03.0-ce-mac60 (23751)) running and it worked fine for me.

**Comment by steals** [comment]
@casi Do you have docker installed from brew-core or from Caskroom? Could you please provide the output of the following command: `brew list|grep docker`

**Comment by casi** [comment]
@steals I just use the [Docker for Mac](https://store.docker.com/editions/community/docker-ce-desktop-mac). 
To be honest I'm afraid I didn't have it running when I ran the codeclimate update. But I did not realize that codeclimate has a dependency on docker. I'm still surprised... ;)

**Comment by exocode** [comment]
Hi there,

I have this problem too. Runnin:

```
$ docker version                                                                                                                     ✔
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.37 (downgraded from 1.39)
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.05.0-ce
  API version:      1.37 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       f150324
  Built:            Wed May  9 22:20:42 2018
  OS/Arch:          linux/amd64
```

```
$ brew list|grep docker                                                                                          
docker
docker-compose
docker-machine
```

```
brew install codeclimate                                                                                                         1 ↵
Updating Homebrew...
==> Installing codeclimate from codeclimate/formulae
==> Downloading https://github.com/codeclimate/codeclimate/archive/v0.85.1.tar.gz
Already downloaded: /Users/janjezek/Library/Caches/Homebrew/downloads/2744111bf485b682934f5c9a34d34dabe11062f28eb6b01138521f7cb56e9a7c--codeclimate-0.85.1.tar.gz
==> make install
Last 15 lines from /Users/janjezek/Library/Logs/Homebrew/codeclimate/01.make:
Error response from daemon: Bad response from Docker engine
Unable to run `docker version', the docker daemon may not be running
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
bin/check: line 11: [: : integer expression expected
Please ensure `docker version' succeeds and try again
make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/codeclimate/homebrew-formulae/issues

```

But I also run Docker for mac.
```
Docker 2.0.0.3 is currently the newest version available.
```

![Bildschirmfoto 2019-03-29 um 19 37 02](https://user-images.githubusercontent.com/1597621/55255107-0cfdba80-525a-11e9-9093-fc768288a3ac.png)

Did I miss something?

**Comment by exocode** [comment]
Ok, got it installed. But don't know how why. 
Sorry for making noise..
